export const data = {
  clothing: [
    {
      id: 1,
      name: "Men's T-Shirt",
      category: "men",
      price: 20.99,
      image: "https://assets.adidas.com/images/w_940,f_auto,q_auto/61f98f8755c64187b9f2af0f00d1150b_9366/IC5491_01_laydown.jpg",
      description: "A classic crew neck t-shirt for men.",
      colors: ["Black", "White", "Gray"],
      sizes: ["S", "M", "L", "XL"],
      material: "Cotton",
      brand: "Adidas"
    },
    {
      id: 2,
      name: "Women's T-Shirt",
      category: "women",
      price: 39.99,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2c8571dc0776493e812c2cbf69f3917d_9366/Adicolor_Trefoil_Boxy_Tee_Green_IN8434_01_laydown.jpg",
      description: "A relaxed fit t-shirt with a stylish design for women.",
      colors: ["Green", "White", "Pink"],
      sizes: ["XS", "S", "M", "L"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 3,
      name: "Kids' Pants",
      category: "kids",
      price: 25.50,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ced651a759b247c49ba6c2118a68a251_9366/3S_TRICOT_JOGGER_S24_Blue_IR4848_01_laydown.jpg",
      description: "Comfortable jogger pants for kids.",
      colors: ["Blue", "Black"],
      sizes: ["2T", "3T", "4T", "5T"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 4,
      name: "Men's Pants",
      category: "men",
      price: 34.99,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/8a66c568147c4d1690076b8834b5f936_9366/Adicolor_Classics_Adibreak_Pants_Blue_IM8223_01_laydown.jpg",
      description: "Classic Adidas track pants for men.",
      colors: ["Blue", "Black"],
      sizes: ["S", "M", "L", "XL"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 5,
      name: "Women's Tank Top",
      category: "women",
      price: 29.99,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/515de41d06c747cb851ba80c6ba25723_9366/Essentials_Rib_Tank_Top_Orange_IR5917_01_laydown.jpg",
      description: "Stylish ribbed tank top for women.",
      colors: ["Orange", "White"],
      sizes: ["XS", "S", "M"],
      material: "Cotton",
      brand: "Adidas"
    },
    {
      id: 6,
      name: "Kids' T-Shirt",
      category: "kids",
      price: 15.99,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3d9525d3d858415e852d23fef013e739_9366/Inter_Miami_CF_23-24_Messi_Away_Jersey_Kids_Black_JE9740_02_laydown.jpg",
      description: "Cool jersey t-shirt for kids.",
      colors: ["Black", "Red"],
      sizes: ["2T", "3T", "4T", "5T"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 7,
      name: "Men's Hoodie",
      category: "men",
      price: 45.50,
      image: "https://assets.adidas.com/images/c_crop,f_auto,fl_lossy,g_north,h_840,q_auto,y_40/h_840/6d8283421af64c0e829a99b15843b859_9366/ALL_SZN_Snack_Attack_French_Terry_Pullover_Hoodie_White_IV7018_01_laydown.jpg",
      description: "Warm and comfortable hoodie for men.",
      colors: ["White", "Gray", "Black"],
      sizes: ["S", "M", "L", "XL"],
      material: "Cotton",
      brand: "Adidas"
    },
    {
      id: 8,
      name: "Women's Jacket",
      category: "women",
      price: 59.99,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/48318e853d0b41ae95d219afcc1d5e1f_9366/adidas_x_FARM_Rio_Tiro_Track_Jacket_Red_IQ4496_01_laydown.jpg",
      description: "Stylish track jacket for women.",
      colors: ["Red", "Blue"],
      sizes: ["XS", "S", "M", "L"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 9,
      name: "Kids' Sweater",
      category: "kids",
      price: 20.00,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ebf031cfa3e34de6a8fe47f933a4a72f_9366/Adicolor_Hoodie_Purple_IP3031_01_laydown.jpg",
      description: "Cozy hoodie for kids.",
      colors: ["Purple", "Black"],
      sizes: ["2T", "3T", "4T", "5T"],
      material: "Cotton",
      brand: "Adidas"
    },
    {
      id: 10,
      name: "Men's Short",
      category: "men",
      price: 24.99,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a5ca563aeb8e4723bdd3ae35011ad7bb_9366/Entrada_22_Shorts_Blue_HG6291_01_laydown.jpg",
      description: "Comfortable shorts for men.",
      colors: ["Blue", "Black"],
      sizes: ["S", "M", "L", "XL"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 11,
      name: "Women's Skirt",
      category: "women",
      price: 35.99,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/64828863c68648fb9bb3ad8700fa8048_9366/Frill_Skort_Black_HA3460_01_laydown.jpg",
      description: "Stylish skirt for women.",
      colors: ["Black", "White"],
      sizes: ["XS", "S", "M", "L"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 12,
      name: "Kids' Shorts",
      category: "kids",
      price: 18.50,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a5ca563aeb8e4723bdd3ae35011ad7bb_9366/Entrada_22_Shorts_Blue_HG6291_01_laydown.jpg",
      description: "Comfortable shorts for kids.",
      colors: ["Blue", "Black"],
      sizes: ["2T", "3T", "4T", "5T"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 13,
      name: "Men's Jersey",
      category: "men",
      price: 29.99,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/5ac7de18d0ab49f1987087ac4abb72ae_9366/Argentina_24_Messi_Home_Jersey_White_IX7790_01_laydown.jpg",
      description: "Official Argentina home jersey for men.",
      colors: ["White", "Blue"],
      sizes: ["S", "M", "L", "XL"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 14,
      name: "Women's Pants",
      category: "women",
      price: 45.99,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9594a95cf94e4c11a6c720fa9b1d960d_9366/adidas_x_FARM_Rio_7-8_Leggings_Blue_IQ4508_01_laydown.jpg",
      description: "Stylish leggings for women.",
      colors: ["Blue", "Black"],
      sizes: ["XS", "S", "M", "L"],
      material: "Polyester",
      brand: "Adidas"
    },
    {
      id: 15,
      name: "Kids' Jacket",
      category: "kids",
      price: 29.50,
      image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/177bb1bc11ee47269a8bafac0006edfc_9366/Winter_Golf_Jacket_Black_IU4937_01_laydown.jpg",
      description: "A cozy jacket with a hood for kids.",
      colors: ["Black", "Blue"],
      sizes: ["2T", "3T", "4T", "5T"],
      material: "Polyester",
      brand: "Adidas"
    },
  ]
};
